/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WizardRouteImport } from './routes/wizard'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardFlaggedRouteImport } from './routes/dashboard/flagged'
import { Route as DashboardSearchesIndexRouteImport } from './routes/dashboard/searches.index'
import { Route as DashboardAlertsIndexRouteImport } from './routes/dashboard/alerts.index'
import { Route as DashboardSearchesNewRouteImport } from './routes/dashboard/searches.new'
import { Route as DashboardSearchesIdRouteImport } from './routes/dashboard/searches.$id'
import { Route as DashboardAlertsSearchIdRouteImport } from './routes/dashboard/alerts.$searchId'
import { Route as DashboardSearchesIdAnalyticsRouteImport } from './routes/dashboard/searches.$id.analytics'

const WizardRoute = WizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFlaggedRoute = DashboardFlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSearchesIndexRoute = DashboardSearchesIndexRouteImport.update({
  id: '/searches/',
  path: '/searches/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAlertsIndexRoute = DashboardAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSearchesNewRoute = DashboardSearchesNewRouteImport.update({
  id: '/searches/new',
  path: '/searches/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSearchesIdRoute = DashboardSearchesIdRouteImport.update({
  id: '/searches/$id',
  path: '/searches/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAlertsSearchIdRoute = DashboardAlertsSearchIdRouteImport.update({
  id: '/alerts/$searchId',
  path: '/alerts/$searchId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSearchesIdAnalyticsRoute =
  DashboardSearchesIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardSearchesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/wizard': typeof WizardRoute
  '/dashboard/flagged': typeof DashboardFlaggedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/alerts/$searchId': typeof DashboardAlertsSearchIdRoute
  '/dashboard/searches/$id': typeof DashboardSearchesIdRouteWithChildren
  '/dashboard/searches/new': typeof DashboardSearchesNewRoute
  '/dashboard/alerts/': typeof DashboardAlertsIndexRoute
  '/dashboard/searches/': typeof DashboardSearchesIndexRoute
  '/dashboard/searches/$id/analytics': typeof DashboardSearchesIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wizard': typeof WizardRoute
  '/dashboard/flagged': typeof DashboardFlaggedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/alerts/$searchId': typeof DashboardAlertsSearchIdRoute
  '/dashboard/searches/$id': typeof DashboardSearchesIdRouteWithChildren
  '/dashboard/searches/new': typeof DashboardSearchesNewRoute
  '/dashboard/alerts': typeof DashboardAlertsIndexRoute
  '/dashboard/searches': typeof DashboardSearchesIndexRoute
  '/dashboard/searches/$id/analytics': typeof DashboardSearchesIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/wizard': typeof WizardRoute
  '/dashboard/flagged': typeof DashboardFlaggedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/alerts/$searchId': typeof DashboardAlertsSearchIdRoute
  '/dashboard/searches/$id': typeof DashboardSearchesIdRouteWithChildren
  '/dashboard/searches/new': typeof DashboardSearchesNewRoute
  '/dashboard/alerts/': typeof DashboardAlertsIndexRoute
  '/dashboard/searches/': typeof DashboardSearchesIndexRoute
  '/dashboard/searches/$id/analytics': typeof DashboardSearchesIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/wizard'
    | '/dashboard/flagged'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/alerts/$searchId'
    | '/dashboard/searches/$id'
    | '/dashboard/searches/new'
    | '/dashboard/alerts/'
    | '/dashboard/searches/'
    | '/dashboard/searches/$id/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/wizard'
    | '/dashboard/flagged'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/alerts/$searchId'
    | '/dashboard/searches/$id'
    | '/dashboard/searches/new'
    | '/dashboard/alerts'
    | '/dashboard/searches'
    | '/dashboard/searches/$id/analytics'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/wizard'
    | '/dashboard/flagged'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/alerts/$searchId'
    | '/dashboard/searches/$id'
    | '/dashboard/searches/new'
    | '/dashboard/alerts/'
    | '/dashboard/searches/'
    | '/dashboard/searches/$id/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  WizardRoute: typeof WizardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wizard': {
      id: '/wizard'
      path: '/wizard'
      fullPath: '/wizard'
      preLoaderRoute: typeof WizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/flagged': {
      id: '/dashboard/flagged'
      path: '/flagged'
      fullPath: '/dashboard/flagged'
      preLoaderRoute: typeof DashboardFlaggedRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/searches/': {
      id: '/dashboard/searches/'
      path: '/searches'
      fullPath: '/dashboard/searches/'
      preLoaderRoute: typeof DashboardSearchesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/alerts/': {
      id: '/dashboard/alerts/'
      path: '/alerts'
      fullPath: '/dashboard/alerts/'
      preLoaderRoute: typeof DashboardAlertsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/searches/new': {
      id: '/dashboard/searches/new'
      path: '/searches/new'
      fullPath: '/dashboard/searches/new'
      preLoaderRoute: typeof DashboardSearchesNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/searches/$id': {
      id: '/dashboard/searches/$id'
      path: '/searches/$id'
      fullPath: '/dashboard/searches/$id'
      preLoaderRoute: typeof DashboardSearchesIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/alerts/$searchId': {
      id: '/dashboard/alerts/$searchId'
      path: '/alerts/$searchId'
      fullPath: '/dashboard/alerts/$searchId'
      preLoaderRoute: typeof DashboardAlertsSearchIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/searches/$id/analytics': {
      id: '/dashboard/searches/$id/analytics'
      path: '/analytics'
      fullPath: '/dashboard/searches/$id/analytics'
      preLoaderRoute: typeof DashboardSearchesIdAnalyticsRouteImport
      parentRoute: typeof DashboardSearchesIdRoute
    }
  }
}

interface DashboardSearchesIdRouteChildren {
  DashboardSearchesIdAnalyticsRoute: typeof DashboardSearchesIdAnalyticsRoute
}

const DashboardSearchesIdRouteChildren: DashboardSearchesIdRouteChildren = {
  DashboardSearchesIdAnalyticsRoute: DashboardSearchesIdAnalyticsRoute,
}

const DashboardSearchesIdRouteWithChildren =
  DashboardSearchesIdRoute._addFileChildren(DashboardSearchesIdRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardFlaggedRoute: typeof DashboardFlaggedRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAlertsSearchIdRoute: typeof DashboardAlertsSearchIdRoute
  DashboardSearchesIdRoute: typeof DashboardSearchesIdRouteWithChildren
  DashboardSearchesNewRoute: typeof DashboardSearchesNewRoute
  DashboardAlertsIndexRoute: typeof DashboardAlertsIndexRoute
  DashboardSearchesIndexRoute: typeof DashboardSearchesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardFlaggedRoute: DashboardFlaggedRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAlertsSearchIdRoute: DashboardAlertsSearchIdRoute,
  DashboardSearchesIdRoute: DashboardSearchesIdRouteWithChildren,
  DashboardSearchesNewRoute: DashboardSearchesNewRoute,
  DashboardAlertsIndexRoute: DashboardAlertsIndexRoute,
  DashboardSearchesIndexRoute: DashboardSearchesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  WizardRoute: WizardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
